<a href="https://colab.research.google.com/github/JuiiiDixit/Jui-Dixit-EDA-AllExpts-25070123059/blob/main/Create_dataset_and_load_datasetipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 10- Create dataset and load dataset
##Name: Jui Dixit
##Class: Entc A3
#PRN: 25070123059
#Date: 20/2/2026

In [ ]:
import pandas as pd
data = {
    "Roll no": [101, 102, 103, 104, 105],
    "Gender": ["Female", "Male","Female","Male","Female"],
    "Department": ["Computer", "IT", "ENTC", "Mechanical","Computer"],
    "CGPA": [8.2, 7.5, 9.1, 6.8, 8.7]
}
df = pd.DataFrame(data)
df.to_csv("student.csv", index=False)
df

   Roll no  Gender  Department  CGPA
0      101  Female    Computer   8.2
1      102    Male          IT   7.5
2      103  Female        ENTC   9.1
3      104    Male  Mechanical   6.8
4      105  Female    Computer   8.7

In [ ]:
df.size

20

In [ ]:
df.shape

(5, 4)

In [ ]:
df.info

<bound method DataFrame.info of    Roll no  Gender  Department  CGPA
0      101  Female    Computer   8.2
1      102    Male          IT   7.5
2      103  Female        ENTC   9.1
3      104    Male  Mechanical   6.8
4      105  Female    Computer   8.7>

In [ ]:
#Access information of column dept
#Access information of PRN 103
#Find out datatype of each column
#Perform mean, median and mode operation
#Insert a new column grade
#Delete gender column
#CGPA of topper
#CGPA of prn 105

In [ ]:
#Access informartion of column departrment
df.Department

0      Computer
1            IT
2          ENTC
3    Mechanical
4      Computer
Name: Department, dtype: object

In [ ]:
#Access information of prn 103
df.loc[2]

Roll no          103
Gender        Female
Department      ENTC
CGPA             9.1
Name: 2, dtype: object

In [ ]:
#Find out datatype of each column
df.dtypes

Roll no         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [ ]:
#Perform mean and median operation
mean1 = df.CGPA.mean()
median1= df.CGPA.median()
print(mean1)
print(median1)

8.059999999999999
8.2

In [ ]:
#Insert a new column
df["Grade"] = ["A", "B", "O", "C","A"]
df

   Roll no  Gender  Department  CGPA Grade
0      101  Female    Computer   8.2     A
1      102    Male          IT   7.5     B
2      103  Female        ENTC   9.1     O
3      104    Male  Mechanical   6.8     C
4      105  Female    Computer   8.7     A

In [ ]:
#CGPA of topper
gpa_of_topper = df.CGPA.max()
print(gpa_of_topper)

9.1

In [ ]:
#Delete gender column
df.drop("Gender", axis = 1, inplace = False)

   Roll no  Department  CGPA
0      101    Computer   8.2
1      102          IT   7.5
2      103        ENTC   9.1
3      104  Mechanical   6.8
4      105    Computer   8.7

In [ ]:
#Access cgpa of prn 103
print(df.loc[4, "CGPA"])

8.7

In [ ]:
#Upload the dataset
import pandas as pd
import numpy as np
df=pd.read_csv('/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.info
print(df.info)

<bound method DataFrame.info of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25                 NaN
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5          11.0
1          200           5            30.0          15.0
2          172           5            28.0          14.0
3          172           6            31.0          17.0
4          208           4            27.0          13.0
..         ...         ...             ...           ...
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

[93 rows x 10 columns]>

In [ ]:
df.head
print(df.head)

<bound method NDFrame.head of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25                 NaN
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5          11.0
1          200           5            30.0          15.0
2          172           5            28.0          14.0
3          172           6            31.0          17.0
4          208           4            27.0          13.0
..         ...         ...             ...           ...
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

[93 rows x 10 columns]>

In [ ]:
df.tail
print(df.tail)

<bound method NDFrame.tail of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25                 NaN
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5          11.0
1          200           5            30.0          15.0
2          172           5            28.0          14.0
3          172           6            31.0          17.0
4          208           4            27.0          13.0
..         ...         ...             ...           ...
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

[93 rows x 10 columns]>

In [ ]:
df.shape
print(df.shape)

(93, 10)

In [ ]:
df.describe
print(df.describe)

<bound method NDFrame.describe of    Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0         Acura  Integra    Small   15.9        25                 NaN
1         Acura   Legend  Midsize   33.9        18  Driver & Passenger
2          Audi       90  Compact   29.1        20         Driver only
3          Audi      100  Midsize   37.7        19  Driver & Passenger
4           BMW     535i  Midsize   30.0        22         Driver only
..          ...      ...      ...    ...       ...                 ...
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
0          140           5            26.5          11.0
1          200           5            30.0          15.0
2          172           5            28.0          14.0
3          172           6            31.0          17.0
4          208           4            27.0          13.0
..         ...         ...             ...           ...
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

[93 rows x 10 columns]>

In [ ]:
df.size
print(df.size)

930