<a href="https://colab.research.google.com/github/JuiiiDixit/Jui-Dixit-EDA-AllExpts-25070123059/blob/main/Data_binning_and_data_formatting_using_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 13: Data binning and data formatting using python
##Name: Jui Dixit
##Class: Entc A3
##PRN: 25070123059
##Date: 20/2/26

In [ ]:
import pandas as pd
import numpy as np
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_sold': [25, 60, 35, 80, 50, 15]
}
df = pd.DataFrame(data)
print("Dataset")
df

Dataset

      Product  Price  Units_sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#Data binning
bins = [0, 10000, 30000, 60000]
labels = ['Low', 'Medium', 'High']
df['Price_Category'] = pd.cut(df['Price'], bins=bins, labels=labels)
df

      Product  Price  Units_sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [8]:
#binning units sold
bins2 = [0, 30, 60, 100]
labels2 = ['Low sales', 'Medium sales', 'High sales']
df['Sales_Category'] = pd.cut(df['Units_sold'], bins=bins2, labels = labels2)
df

      Product  Price  Units_sold Price_Category Sales_Category
0      Laptop  55000          25           High      Low sales
1      Mobile  20000          60         Medium   Medium sales
2      Tablet  30000          35         Medium   Medium sales
3  Headphones   2000          80            Low     High sales
4  Smartwatch   8000          50            Low   Medium sales
5      Camera  45000          15           High      Low sales

In [11]:
#Data formating
#Convert data type
print(df.dtypes)
df['Units_sold'] = df['Units_sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_sold         float64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price                int64
Units_sold         float64
Price_Category    category
Sales_Category    category
dtype: object

In [12]:
df

      Product  Price  Units_sold Price_Category Sales_Category
0      Laptop  55000        25.0           High      Low sales
1      Mobile  20000        60.0         Medium   Medium sales
2      Tablet  30000        35.0         Medium   Medium sales
3  Headphones   2000        80.0            Low     High sales
4  Smartwatch   8000        50.0            Low   Medium sales
5      Camera  45000        15.0           High      Low sales

In [14]:
#Convert price into float
print(df.dtypes)
df['Price'] = df['Price'].astype(float)
print(df.dtypes)

Product             object
Price              float64
Units_sold         float64
Price_Category    category
Sales_Category    category
dtype: object
Product             object
Price              float64
Units_sold         float64
Price_Category    category
Sales_Category    category
dtype: object

In [15]:
df

      Product    Price  Units_sold Price_Category Sales_Category
0      Laptop  55000.0        25.0           High      Low sales
1      Mobile  20000.0        60.0         Medium   Medium sales
2      Tablet  30000.0        35.0         Medium   Medium sales
3  Headphones   2000.0        80.0            Low     High sales
4  Smartwatch   8000.0        50.0            Low   Medium sales
5      Camera  45000.0        15.0           High      Low sales

In [16]:
#Convert text to uppercase
df['Product'] = df['Product'].str.upper()
df

      Product    Price  Units_sold Price_Category Sales_Category
0      LAPTOP  55000.0        25.0           High      Low sales
1      MOBILE  20000.0        60.0         Medium   Medium sales
2      TABLET  30000.0        35.0         Medium   Medium sales
3  HEADPHONES   2000.0        80.0            Low     High sales
4  SMARTWATCH   8000.0        50.0            Low   Medium sales
5      CAMERA  45000.0        15.0           High      Low sales

In [17]:
#Additional operations
#sort data
sorted_df = df.sort_values(by = 'Price')
sorted_df

      Product    Price  Units_sold Price_Category Sales_Category
3  HEADPHONES   2000.0        80.0            Low     High sales
4  SMARTWATCH   8000.0        50.0            Low   Medium sales
1      MOBILE  20000.0        60.0         Medium   Medium sales
2      TABLET  30000.0        35.0         Medium   Medium sales
5      CAMERA  45000.0        15.0           High      Low sales
0      LAPTOP  55000.0        25.0           High      Low sales

In [18]:
#Display unique values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [20]:
#Dataset: Food delivery orders
import pandas as pd
import numpy as np
data = {
    'Order_ID': ['01', '02', '03', '04', '05', '06', '07', '08'],
    'Order_Value': [250, 450, 120, 600, 300, 150, 500, 220],
    'Delivery_time': [30, 45, 25, 60, 35, 20, 50, 28],
    'Distance_km': [5, 8, 3, 10, 6, 2, 9, 4]
}
df = pd.DataFrame(data)
df

  Order_ID  Order_Value  Delivery_time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [32]:
#data binning
bins1 = [0, 20, 40, 60]
labels1 = ['Very Quick', 'Quick', 'Slow']
df['Delivery_speed'] = pd.cut(df['Delivery_speed'], bins=bins1, labels=labels1)
df

  Order_ID  Order_Value  Delivery_time  Distance_km Delivery_speed
0       01          250             30            5          Quick
1       02          450             45            8           Slow
2       03          120             25            3          Quick
3       04          600             60           10           Slow
4       05          300             35            6          Quick
5       06          150             20            2     Very Quick
6       07          500             50            9           Slow
7       08          220             28            4          Quick

In [33]:
#Convert distance to float
df['Distance_km'] = df['Distance_km'].astype(float)
df

  Order_ID  Order_Value  Delivery_time  Distance_km Delivery_speed
0       01          250             30          5.0          Quick
1       02          450             45          8.0           Slow
2       03          120             25          3.0          Quick
3       04          600             60         10.0           Slow
4       05          300             35          6.0          Quick
5       06          150             20          2.0     Very Quick
6       07          500             50          9.0           Slow
7       08          220             28          4.0          Quick

In [34]:
#Convert delivery speed to uppercase
df['Delivery_speed'] = df['Delivery_speed'].str.upper()
df

  Order_ID  Order_Value  Delivery_time  Distance_km Delivery_speed
0       01          250             30          5.0          QUICK
1       02          450             45          8.0           SLOW
2       03          120             25          3.0          QUICK
3       04          600             60         10.0           SLOW
4       05          300             35          6.0          QUICK
5       06          150             20          2.0     VERY QUICK
6       07          500             50          9.0           SLOW
7       08          220             28          4.0          QUICK

In [36]:
#Sorting
print(df.sort_values(by = 'Order_Value'))
df

  Order_ID  Order_Value  Delivery_time  Distance_km Delivery_speed
2       03          120             25          3.0          QUICK
5       06          150             20          2.0     VERY QUICK
7       08          220             28          4.0          QUICK
0       01          250             30          5.0          QUICK
4       05          300             35          6.0          QUICK
1       02          450             45          8.0           SLOW
6       07          500             50          9.0           SLOW
3       04          600             60         10.0           SLOW

  Order_ID  Order_Value  Delivery_time  Distance_km Delivery_speed
0       01          250             30          5.0          QUICK
1       02          450             45          8.0           SLOW
2       03          120             25          3.0          QUICK
3       04          600             60         10.0           SLOW
4       05          300             35          6.0          QUICK
5       06          150             20          2.0     VERY QUICK
6       07          500             50          9.0           SLOW
7       08          220             28          4.0          QUICK