<a href="https://colab.research.google.com/github/JuiiiDixit/Jui-Dixit-EDA-AllExpts-25070123059/blob/main/Data_normalization_and_data_type_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 14: Data Normalization and data type conversion
#Part-A: Data Normalization
##Name: Jui Dixit
##Class: ENTC A3
##PRN: 25070123059
##Date: 1/4/26

In [3]:
#Dataset
import pandas as pd
import numpy as np
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_sold': [25, 60, 35, 80, 50, 15],
    'Discount': [10, 15, 12, 20, 18, 8]
}
df = pd.DataFrame(data)
df

      Product  Price  Units_sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [8]:
#1. Min-Max Normalization
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
df['Discount_MinMax'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())
print("\nMin-Max Normalized Price")
df[['Product', 'Price', 'Discount_MinMax', 'Price_MinMax']]

Min-Max Normalized Price

      Product  Price  Discount_MinMax  Price_MinMax
0      Laptop  55000         0.166667      1.000000
1      Mobile  20000         0.583333      0.339623
2      Tablet  30000         0.333333      0.528302
3  Headphones   2000         1.000000      0.000000
4  Smartwatch   8000         0.833333      0.113208
5      Camera  45000         0.000000      0.811321

In [9]:
#Normalize Multiple columns
cols = ['Price', 'Units_sold', 'Discount']
df_norm = (df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())
print("\nNormalized dataset")
df_norm

Normalized dataset

      Price  Units_sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [12]:
#2. Z-score Normalization
df['Units_Zscore'] = (df['Units_sold'] - df['Units_sold'].mean()) / df['Units_sold'].std()
print("\nZ-score Normalized Units sold")
(df[['Product', 'Units_sold', 'Units_Zscore']])

Z-score Normalized Units sold

      Product  Units_sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [13]:
#3. Decimal Scaling
df['Price_decimal'] = df['Price'] / 100000
print("\nDecimal scaled Price")
df[['Product', 'Price', 'Price_decimal']]

Decimal scaled Price

      Product  Price  Price_decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

#Part B: Turning categorical variables into quantitative variables in python

In [14]:
data = {
    'Order_ID': [101, 102, 103, 104, 105, 106],
    'Customer_Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Payment_method': ['Credit Card', 'PayPal', 'Cash', 'Credit Card', 'PayPal', 'Cash'],
    'Product_category': ['Electronics', 'Clothing', 'Electronics', 'Clothing', 'Electronics', 'Clothing'],
    'City': ["Mumbai", "Delhi", "Mumbai", "Delhi", "Mumbai", "Delhi"],
    'Order_value': [4500, 2300, 3200, 5200, 1800, 4100]

}
df = pd.DataFrame(data)
df

,Order_ID,Customer_Gender,Payment_method,Product_category,City,Order_value
0,101,Male,Credit Card,Electronics,Mumbai,4500
1,102,Female,PayPal,Clothing,Delhi,2300
2,103,Male,Cash,Electronics,Mumbai,3200
3,104,Female,Credit Card,Clothing,Delhi,5200
4,105,Male,PayPal,Electronics,Mumbai,1800
5,106,Female,Cash,Clothing,Delhi,4100

In [17]:
#Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df

,Order_ID,Customer_Gender,Payment_method,Product_category,City,Order_value,Gender_Label
0,101,Male,Credit Card,Electronics,Mumbai,4500,1
1,102,Female,PayPal,Clothing,Delhi,2300,0
2,103,Male,Cash,Electronics,Mumbai,3200,1
3,104,Female,Credit Card,Clothing,Delhi,5200,0
4,105,Male,PayPal,Electronics,Mumbai,1800,1
5,106,Female,Cash,Clothing,Delhi,4100,0

In [18]:
#Method 2: One-hot encoding
df_encoded = pd.get_dummies(df, columns=['Payment_method'])
df_encoded

,Order_ID,Customer_Gender,Product_category,City,Order_value,Gender_Label,Payment_method_Cash,Payment_method_Credit Card,Payment_method_PayPal
0,101,Male,Electronics,Mumbai,4500,1,False,True,False
1,102,Female,Clothing,Delhi,2300,0,False,False,True
2,103,Male,Electronics,Mumbai,3200,1,True,False,False
3,104,Female,Clothing,Delhi,5200,0,False,True,False
4,105,Male,Electronics,Mumbai,1800,1,False,False,True
5,106,Female,Clothing,Delhi,4100,0,True,False,False

In [20]:
#Method 3: Dummy encoding (Drop first)
df_dummy = pd.get_dummies(df, columns=['Product_category'], drop_first=True)
df_dummy

,Order_ID,Customer_Gender,Payment_method,City,Order_value,Gender_Label,Product_category_Electronics
0,101,Male,Credit Card,Mumbai,4500,1,True
1,102,Female,PayPal,Delhi,2300,0,False
2,103,Male,Cash,Mumbai,3200,1,True
3,104,Female,Credit Card,Delhi,5200,0,False
4,105,Male,PayPal,Mumbai,1800,1,True
5,106,Female,Cash,Delhi,4100,0,False

#New Dataset operations

In [21]:
df = pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")

In [32]:
#Min Max normalization
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
df['Rating_MinMax'] = (df['Rating'] - df['Rating'].min()) / (df['Rating'].max() - df['Rating'].min())
df['Reviews'] = (df['Reviews'] - df['Reviews'].min()) / (df['Reviews'].max() - df['Reviews'].min())
df['Units_Sold'] = (df['Units_Sold'] - df['Units_Sold'].min()) / (df['Units_Sold'].max() - df['Units_Sold'].min())
print("\nMin-Max Normalized Price")
df[['Product_Name', 'Price', 'Rating', 'Reviews', 'Units_Sold']]

Min-Max Normalized Price

                   Product_Name  Price  Rating   Reviews  Units_Sold
0                Wireless Mouse    799     4.3  0.291005    0.518519
1             Bluetooth Speaker   1499     4.5  0.148148    0.277778
2                  USB Keyboard    699     4.1  0.119048    0.203704
3                Gaming Headset   2499     4.6  0.444444    0.629630
4                    Smartwatch   3999     4.4  0.695767    0.833333
5                    Power Bank   1199     4.2  0.351852    0.592593
6                  Laptop Stand    899     4.0  0.052910    0.129630
7                        Webcam   1899     4.3  0.185185    0.351852
8                  Portable SSD   5499     4.7  0.378307    0.481481
9              Wireless Charger    999     4.2  0.089947    0.222222
10  Noise Cancelling Headphones   7999     4.6  1.000000    1.000000
11          Mechanical Keyboard   4599     4.5  0.444444    0.407407
12                 Gaming Mouse   1599     4.4  0.232804    0.500000
13                 Tablet Stand    699     4.1  0.031746    0.092593
14                      USB Hub    899     4.2  0.119048    0.240741
15          External Hard Drive   6499     4.6  0.497354    0.444444
16            Smartphone Tripod   1199     4.3  0.089947    0.259259
17              Laptop Backpack   1999     4.4  0.312169    0.648148
18            Bluetooth Earbuds   2999     4.5  0.814815    0.851852
19                LED Desk Lamp   1299     4.3  0.148148    0.351852
20                 Phone Holder    499     4.0  0.000000    0.148148
21            Wireless Keyboard   2499     4.4  0.272487    0.444444
22             Portable Monitor   8999     4.6  0.219577    0.185185
23                   Smart Plug    799     4.2  0.079365    0.259259
24                  WiFi Router   3499     4.5  0.444444    0.592593
25              Graphics Tablet   4599     4.4  0.148148    0.166667
26                   VR Headset  12999     4.7  0.708995    0.129630
27                   Microphone   2199     4.3  0.232804    0.370370
28             Smart Light Bulb    699     4.2  0.121693    0.314815
29           Laptop Cooling Pad   1499     4.3  0.150794    0.351852
30                Action Camera   9999     4.6  0.444444    0.240741
31               Smart Doorbell   5999     4.5  0.351852    0.203704
32              Streaming Stick   3499     4.4  0.550265    0.666667
33           Portable Projector  11999     4.6  0.272487    0.092593
34                 Gaming Chair  15999     4.7  0.444444    0.037037
35               Desk Organizer    599     4.1  0.007937    0.166667
36              USB Flash Drive    799     4.2  0.126984    0.462963
37       Phone Screen Protector    299     4.0  0.047619    0.574074
38                Laptop Sleeve    999     4.3  0.079365    0.259259
39           Wireless Presenter   1499     4.4  0.026455    0.111111
40         Tablet Keyboard Case   2999     4.5  0.113757    0.148148
41             Smart Thermostat  10999     4.6  0.206349    0.074074
42              Security Camera   4999     4.4  0.444444    0.351852
43                 Drone Camera  24999     4.7  0.365079    0.000000
44              Electric Kettle   1999     4.3  0.259259    0.444444
45                    Air Fryer   7999     4.6  0.470899    0.240741
46                 Robot Vacuum  18999     4.5  0.325397    0.092593
47                  Smart Scale   2499     4.4  0.148148    0.185185
48          Digital Photo Frame   3499     4.3  0.119048    0.148148
49                 Portable Fan    999     4.2  0.089947    0.314815

In [30]:
#Z-score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print("\nZ-score Normalized Units sold")
(df[['Product_Name', 'Units_Sold', 'Units_Zscore']])

Z-score Normalized Units sold

                   Product_Name  Units_Sold  Units_Zscore
0                Wireless Mouse         350      0.812282
1             Bluetooth Speaker         220     -0.260855
2                  USB Keyboard         180     -0.591051
3                Gaming Headset         410      1.307576
4                    Smartwatch         520      2.215615
5                    Power Bank         390      1.142478
6                  Laptop Stand         140     -0.921247
7                        Webcam         260      0.069341
8                  Portable SSD         330      0.647184
9              Wireless Charger         190     -0.508502
10  Noise Cancelling Headphones         610      2.958556
11          Mechanical Keyboard         290      0.316988
12                 Gaming Mouse         340      0.729733
13                 Tablet Stand         120     -1.086345
14                      USB Hub         200     -0.425953
15          External Hard Drive         310      0.482086
16            Smartphone Tripod         210     -0.343404
17              Laptop Backpack         420      1.390125
18            Bluetooth Earbuds         530      2.298164
19                LED Desk Lamp         260      0.069341
20                 Phone Holder         150     -0.838698
21            Wireless Keyboard         310      0.482086
22             Portable Monitor         170     -0.673600
23                   Smart Plug         210     -0.343404
24                  WiFi Router         390      1.142478
25              Graphics Tablet         160     -0.756149
26                   VR Headset         140     -0.921247
27                   Microphone         270      0.151890
28             Smart Light Bulb         240     -0.095757
29           Laptop Cooling Pad         260      0.069341
30                Action Camera         200     -0.425953
31               Smart Doorbell         180     -0.591051
32              Streaming Stick         430      1.472674
33           Portable Projector         120     -1.086345
34                 Gaming Chair          90     -1.333992
35               Desk Organizer         160     -0.756149
36              USB Flash Drive         320      0.564635
37       Phone Screen Protector         380      1.059929
38                Laptop Sleeve         210     -0.343404
39           Wireless Presenter         130     -1.003796
40         Tablet Keyboard Case         150     -0.838698
41             Smart Thermostat         110     -1.168894
42              Security Camera         260      0.069341
43                 Drone Camera          70     -1.499090
44              Electric Kettle         310      0.482086
45                    Air Fryer         200     -0.425953
46                 Robot Vacuum         120     -1.086345
47                  Smart Scale         170     -0.673600
48          Digital Photo Frame         150     -0.838698
49                 Portable Fan         240     -0.095757

In [31]:
#Decimal scaling-review/price
df['Price_decimal'] = df['Price'] / 100000
print("\nDecimal scaled Price")
df

Decimal scaled Price

,Product_ID,Product_Name,Price,Rating,Reviews,Units_Sold,Price_MinMax,Rating_MinMax,Units_Zscore,Price_decimal
0,P101,Wireless Mouse,799,4.3,1520,350,0.020243,0.428571,0.812282,0.00799
1,P102,Bluetooth Speaker,1499,4.5,980,220,0.048583,0.714286,-0.260855,0.01499
2,P103,USB Keyboard,699,4.1,870,180,0.016194,0.142857,-0.591051,0.00699
3,P104,Gaming Headset,2499,4.6,2100,410,0.089069,0.857143,1.307576,0.02499
4,P105,Smartwatch,3999,4.4,3050,520,0.149798,0.571429,2.215615,0.03999
5,P106,Power Bank,1199,4.2,1750,390,0.036437,0.285714,1.142478,0.01199
6,P107,Laptop Stand,899,4.0,620,140,0.024291,0.000000,-0.921247,0.00899
7,P108,Webcam,1899,4.3,1120,260,0.064777,0.428571,0.069341,0.01899
8,P109,Portable SSD,5499,4.7,1850,330,0.210526,1.000000,0.647184,0.05499
9,P110,Wireless Charger,999,4.2,760,190,0.028340,0.285714,-0.508502,0.00999
10,P111,Noise Cancelling Headphones,7999,4.6,4200,610,0.311741,0.857143,2.958556,0.07999
11,P112,Mechanical Keyboard,4599,4.5,2100,290,0.174089,0.714286,0.316988,0.04599
12,P113,Gaming Mouse,1599,4.4,1300,340,0.052632,0.571429,0.729733,0.01599
13,P114,Tablet Stand,699,4.1,540,120,0.016194,0.142857,-1.086345,0.00699
14,P115,USB Hub,899,4.2,870,200,0.024291,0.285714,-0.425953,0.00899
15,P116,External Hard Drive,6499,4.6,2300,310,0.251012,0.857143,0.482086,0.06499
16,P117,Smartphone Tripod,1199,4.3,760,210,0.036437,0.428571,-0.343404,0.01199
17,P118,Laptop Backpack,1999,4.4,1600,420,0.068826,0.571429,1.390125,0.01999
18,P119,Bluetooth Earbuds,2999,4.5,3500,530,0.109312,0.714286,2.298164,0.02999
19,P120,LED Desk Lamp,1299,4.3,980,260,0.040486,0.428571,0.069341,0.01299
20,P121,Phone Holder,499,4.0,420,150,0.008097,0.000000,-0.838698,0.00499
21,P122,Wireless Keyboard,2499,4.4,1450,310,0.089069,0.571429,0.482086,0.02499
22,P123,Portable Monitor,8999,4.6,1250,170,0.352227,0.857143,-0.673600,0.08999
23,P124,Smart Plug,799,4.2,720,210,0.020243,0.285714,-0.343404,0.00799
24,P125,WiFi Router,3499,4.5,2100,390,0.129555,0.714286,1.142478,0.03499
25,P126,Graphics Tablet,4599,4.4,980,160,0.174089,0.571429,-0.756149,0.04599
26,P127,VR Headset,12999,4.7,3100,140,0.514170,1.000000,-0.921247,0.12999
27,P128,Microphone,2199,4.3,1300,270,0.076923,0.428571,0.151890,0.02199
28,P129,Smart Light Bulb,699,4.2,880,240,0.016194,0.285714,-0.095757,0.00699
29,P130,Laptop Cooling Pad,1499,4.3,990,260,0.048583,0.428571,0.069341,0.01499
30,P131,Action Camera,9999,4.6,2100,200,0.392713,0.857143,-0.425953,0.09999
31,P132,Smart Doorbell,5999,4.5,1750,180,0.230769,0.714286,-0.591051,0.05999
32,P133,Streaming Stick,3499,4.4,2500,430,0.129555,0.571429,1.472674,0.03499
33,P134,Portable Projector,11999,4.6,1450,120,0.473684,0.857143,-1.086345,0.11999
34,P135,Gaming Chair,15999,4.7,2100,90,0.635628,1.000000,-1.333992,0.15999
35,P136,Desk Organizer,599,4.1,450,160,0.012146,0.142857,-0.756149,0.00599
36,P137,USB Flash Drive,799,4.2,900,320,0.020243,0.285714,0.564635,0.00799
37,P138,Phone Screen Protector,299,4.0,600,380,0.000000,0.000000,1.059929,0.00299
38,P139,Laptop Sleeve,999,4.3,720,210,0.028340,0.428571,-0.343404,0.00999
39,P140,Wireless Presenter,1499,4.4,520,130,0.048583,0.571429,-1.003796,0.01499
40,P141,Tablet Keyboard Case,2999,4.5,850,150,0.109312,0.714286,-0.838698,0.02999
41,P142,Smart Thermostat,10999,4.6,1200,110,0.433198,0.857143,-1.168894,0.10999
42,P143,Security Camera,4999,4.4,2100,260,0.190283,0.571429,0.069341,0.04999
43,P144,Drone Camera,24999,4.7,1800,70,1.000000,1.000000,-1.499090,0.24999
44,P145,Electric Kettle,1999,4.3,1400,310,0.068826,0.428571,0.482086,0.01999
45,P146,Air Fryer,7999,4.6,2200,200,0.311741,0.857143,-0.425953,0.07999
46,P147,Robot Vacuum,18999,4.5,1650,120,0.757085,0.714286,-1.086345,0.18999
47,P148,Smart Scale,2499,4.4,980,170,0.089069,0.571429,-0.673600,0.02499
48,P149,Digital Photo Frame,3499,4.3,870,150,0.129555,0.428571,-0.838698,0.03499
49,P150,Portable Fan,999,4.2,760,240,0.028340,0.285714,-0.095757,0.00999

In [39]:
df = pd.read_csv("/content/Student-Dataset.csv")

In [40]:
#Label encoding placement status
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Placement_Status'] = le.fit_transform(df['Placement_Status'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,1,450000
1,102,Male,IT,7.5,1,85,0,0
2,103,Female,ENTC,9.1,0,96,1,550000
3,104,Male,Mechanical,6.8,2,78,0,0
4,105,Female,Computer,8.7,0,88,1,480000
5,106,Male,Civil,7.2,3,72,0,0
6,107,Female,IT,8.9,0,91,1,500000
7,108,Male,Computer,6.5,1,80,0,0
8,109,Female,ENTC,7.8,0,84,1,420000
9,110,Male,Mechanical,7.0,2,76,0,0

In [41]:
#One hot encding- Department
df_encoded = pd.get_dummies(df, columns=['Department'])
df_encoded

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,1,450000,False,True,False,False,False
1,102,Male,7.5,1,85,0,0,False,False,False,True,False
2,103,Female,9.1,0,96,1,550000,False,False,True,False,False
3,104,Male,6.8,2,78,0,0,False,False,False,False,True
4,105,Female,8.7,0,88,1,480000,False,True,False,False,False
5,106,Male,7.2,3,72,0,0,True,False,False,False,False
6,107,Female,8.9,0,91,1,500000,False,False,False,True,False
7,108,Male,6.5,1,80,0,0,False,True,False,False,False
8,109,Female,7.8,0,84,1,420000,False,False,True,False,False
9,110,Male,7.0,2,76,0,0,False,False,False,False,True

In [42]:
#Dummies- Department
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)
df_dummy

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,1,450000,True,False,False,False
1,102,Male,7.5,1,85,0,0,False,False,True,False
2,103,Female,9.1,0,96,1,550000,False,True,False,False
3,104,Male,6.8,2,78,0,0,False,False,False,True
4,105,Female,8.7,0,88,1,480000,True,False,False,False
5,106,Male,7.2,3,72,0,0,False,False,False,False
6,107,Female,8.9,0,91,1,500000,False,False,True,False
7,108,Male,6.5,1,80,0,0,True,False,False,False
8,109,Female,7.8,0,84,1,420000,False,True,False,False
9,110,Male,7.0,2,76,0,0,False,False,False,True