<a href="https://colab.research.google.com/github/JuiiiDixit/Jui-Dixit-EDA-AllExpts-25070123059/blob/main/Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 12: Data Wrangling
##Name: Jui Dixit
##Class: EnTC A3
##PRN: 25070123059
##Date: 18/3/26

#To perform preprocessing on a dataset and dealing with missing values

In [1]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'C1': [11,21, np.nan], 'C2': [15, np.nan, np.nan], 'C3': [10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [2]:
df1.isna () #Boolean values

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [3]:
df1.notna()

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [4]:
df1.isna().sum() #Columnwise na values

C1    1
C2    2
C3    0
dtype: int64

In [5]:
df1.dropna ()  #NaN rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [6]:
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [7]:
df1.fillna(value='DEFAULT')

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [8]:
df1.fillna(df1.mean())  #Mean values of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [13]:
#Preprocessing on a dataset 1
import pandas as pd

data = {
    "Roll no": [101,102,103,104],
    "Name": ["Asha", "Rohan", "Meera", "Karan"],
    "Age": [20, "-",21,"22"],
    "Marks": [85,90,"-",88],
    "Department": ["CSE", "IT", "cse", "ENTC"],
    "Admission_date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023"]
}

df = pd.DataFrame(data)
#Save as CSV
df.to_csv("student_data.csv", index = False)

In [17]:
import pandas as pd
import numpy as np

#Step 1: Load the dataset
df= pd.read_csv("student_data.csv")

print("Original data:")
print(df)

Original data:
   Roll no   Name Age Marks Department Admission_date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        cse     05-06-2023
3      104  Karan  22    88       ENTC     07-06-2023

In [20]:
df.replace("-", np.nan, inplace = True)
df

   Roll no   Name  Age Marks Department Admission_date
0      101   Asha   20    85        CSE     01-06-2023
1      102  Rohan  NaN    90         IT     03-06-2023
2      103  Meera   21   NaN        cse     05-06-2023
3      104  Karan   22    88       ENTC     07-06-2023

In [21]:
#Step 2: Replace '-' with NaN to mark the missing values
df.replace("-", np.nan, inplace = True)
#Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors = 'coerce')
df["Marks"] = pd.to_numeric(df["Marks"], errors = 'coerce')

'''When converting data(like strings to datetime),
if some values are invalid or cannot be converted,
instead of throwing an error, it will:
Replace those invalid values with NaT(Not a Time)'''
df

   Roll no   Name   Age  Marks Department Admission_date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        cse     05-06-2023
3      104  Karan  22.0   88.0       ENTC     07-06-2023

In [22]:
#Step 3: Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Roll no           0
Name              0
Age               1
Marks             1
Department        0
Admission_date    0
dtype: int64

In [23]:
#Fill missing marks with median
df["Marks"].fillna(df["Marks"].median(), inplace = True)
df

/tmp/ipykernel_174/3133186580.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace = True)

   Roll no   Name   Age  Marks Department Admission_date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0   88.0        cse     05-06-2023
3      104  Karan  22.0   88.0       ENTC     07-06-2023

In [24]:
#Fill missing age with number
df["Age"].fillna(df["Age"].mode()[0], inplace = True)
df

/tmp/ipykernel_174/1135468299.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mode()[0], inplace = True)

   Roll no   Name   Age  Marks Department Admission_date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan  20.0   90.0         IT     03-06-2023
2      103  Meera  21.0   88.0        cse     05-06-2023
3      104  Karan  22.0   88.0       ENTC     07-06-2023

In [25]:
print(df.isnull().sum())

Roll no           0
Name              0
Age               0
Marks             0
Department        0
Admission_date    0
dtype: int64

In [27]:
#Step 5: Fix inconsistent text formatting
df["Department"] = df["Department"].str.upper()
df

   Roll no   Name   Age  Marks Department Admission_date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan  20.0   90.0         IT     03-06-2023
2      103  Meera  21.0   88.0        CSE     05-06-2023
3      104  Karan  22.0   88.0       ENTC     07-06-2023

In [28]:
#Step 6: Convert admission date to standard date time format
df["Admission_date"] = pd.to_datetime(df["Admission_date"], errors = 'coerce')
df

'''invalid dates like "abc" or "32-06-2023

   Roll no   Name   Age  Marks Department Admission_date
0      101   Asha  20.0   85.0        CSE     2023-01-06
1      102  Rohan  20.0   90.0         IT     2023-03-06
2      103  Meera  21.0   88.0        CSE     2023-05-06
3      104  Karan  22.0   88.0       ENTC     2023-07-06

In [29]:
#Step 7: Show cleaned data
print("\nCleaned Data:")
print(df)

Cleaned Data:
   Roll no   Name   Age  Marks Department Admission_date
0      101   Asha  20.0   85.0        CSE     2023-01-06
1      102  Rohan  20.0   90.0         IT     2023-03-06
2      103  Meera  21.0   88.0        CSE     2023-05-06
3      104  Karan  22.0   88.0       ENTC     2023-07-06

In [30]:
#Step 8: Save cleaned dataset
df.to_csv("\nCleaned_student_data.csv", index = False)
print("\nCleaned CSV file saved as cleaned_student_data.csv")

Cleaned CSV file saved as cleaned_student_data.csv

In [34]:
#Working with missing values on dataset 2
df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [35]:
df.isna().sum() #Attributes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [37]:
#Imputing the missing value
#1. Luggage room
df['Luggage.room']= df['Luggage.room'].fillna(value = df['Luggage.room'].mean())

In [38]:
#2. Rear.seat.room
df["Rear.seat.room"] = df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].mean())

In [40]:
#Airbags
df['AirBags']=df['AirBags'].fillna(value=df['AirBags'].mode().values[0])

In [41]:
#save cleaned dataset
df.to_csv("cleaned_Cars93.csv", index = False)